version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8058:8080"
    environment:
      - RUST_LOG=info
    restart: always

networks:
  default:
    driver: bridge
