version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
    volumes:
      - ./data:/usr/src/app/data
    restart: unless-stopped

networks:
  default:
    driver: bridge
